import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRef } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const audioRef = useRef();


  // const play = () => {
  //   if (audioRef.current) {
  //     audioRef.current.play()
  //   } else {
  //     Throw error
  //   }
  // }
  return (
    <>
      <Head>
        <title>PARAKUM THALIKA(BOUNCE)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{color:'red', display:'flex', flexDirection:'column',alignItems:'center', justifyContent:'center', height:'100vh'}}>
        <h1>Bounce me daddy</h1>
        <Link href={'/bounce'}>
        <button  className='customBtn' style={{margin:'2em 0 0 0', padding:'1em 2em', borderRadius:'20em', outline:'none', border:'none', cursor:'pointer', transition:"all 0.3s ease"}}>
          Bounce
        </button>

        {/* <button onClick={play}>Play</button> */}
      {/* <audio ref={audioRef} src='/nammaPayyan.mp3' /> */}
        
        </Link>
      </main>
    </>
  )
}
